org: spectacular-domains
app: testapp
service: configuration

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

package:
  include:
    - dist/** # Include the dist folder and its contents
